// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.10.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../../frb_generated.dart';
import '../types.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:meta/meta.dart' as meta;

Future<AttendanceData> parseAttendance({
  required String html,
  required String sem,
}) => RustLib.instance.api.crateApiVtopParaserParseattnParseAttendance(
  html: html,
  sem: sem,
);

Future<FullAttendanceData> parseFullAttendance({
  required String html,
  required String sem,
  required String courseId,
  required String courseType,
}) => RustLib.instance.api.crateApiVtopParaserParseattnParseFullAttendance(
  html: html,
  sem: sem,
  courseId: courseId,
  courseType: courseType,
);
