// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'vtop_errors.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`, `fmt`

@freezed
sealed class VtopError with _$VtopError implements FrbException {
  const VtopError._();

  const factory VtopError.networkError() = VtopError_NetworkError;
  const factory VtopError.vtopServerError() = VtopError_VtopServerError;
  const factory VtopError.authenticationFailed(String field0) =
      VtopError_AuthenticationFailed;
  const factory VtopError.registrationParsingError() =
      VtopError_RegistrationParsingError;
  const factory VtopError.invalidCredentials() = VtopError_InvalidCredentials;
  const factory VtopError.sessionExpired() = VtopError_SessionExpired;
  const factory VtopError.parseError(String field0) = VtopError_ParseError;
  const factory VtopError.configurationError(String field0) =
      VtopError_ConfigurationError;
  const factory VtopError.captchaRequired() = VtopError_CaptchaRequired;
  const factory VtopError.invalidResponse() = VtopError_InvalidResponse;
}
